### ISSUE TITLE
Mail Chimp Fix

### ISSUE THREAD

**Issue by tawana0518** [NJIT-WIS/project-2-dream-team#79]
The following code had changes completed:

mailchimp.js: https://github.com/NJIT-WIS/project-2-dream-team/pull/74/files
subscribe.js: https://github.com/NJIT-WIS/project-2-dream-team/pull/74/commits/91d12a097c8a71494de0e8f61658f3a046f76ca0

Mailchimp path from subscribe.js was changed 
from: import { addSubscriber } from '../../../../../../mailchimp'
To: import { addSubscriber } from 'mailchimp'

**Comment by rk864** [comment]
Hey @tawana0518 ,

As discussed, The updated subscribe.js file looks almost correct, but we have to make sure we're importing the addSubscriber function properly. If the mailchimp.js file is located at the project root, we should use the relative path to import the function:

import { addSubscriber } from '../../mailchimp';

Now, This is working at local but I will check the major issue why it's not working post deployment.

**Comment by rk864** [comment]
Future reference for the bug : https://github.com/NJIT-WIS/project-2-dream-team/issues/72

**Comment by tawana0518** [comment]
Issue has been reopen as mailchimp is only working on the local level but no longer at post deplyment.

**Comment by tawana0518** [comment]
Closing this issue as issue #72 is current in progress.
